services:
  android:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - API_LEVEL=33
        - CMD_LINE_VERSION=11076708_latest
        - IMG_TYPE=google_apis_playstore
        - GPU_ACCELERATED=true
    container_name: android
    environment:
      - RAM_SIZE=8G
      - DISK_SIZE=64G
      - CPU_CORES=8
      - DISABLE_ANIMATION=false
      - DISABLE_HIDDEN_POLICY=true
      - SKIP_AUTH=true
      - TZ=America/Bogota
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/dri:/dev/dri
    ports:
      - "5554:5554"
      - "127.0.0.1:5555:5555"
    volumes:
      - ./keys/adbkey:/root/.android/adbkey:ro
      - ./keys/adbkey.pub:/root/.android/adbkey.pub:ro
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    tty: true
    stdin_open: true
    restart: unless-stopped
