version: "4"
services:
  android-emulator:
    build:
      context: .
      args:
        - API_LEVEL=34
        - CMD_LINE_VERSION=11076708_latest
        - IMG_TYPE=google_apis
    ports:
      - 5554:5554
      - 127.0.0.1:5555:5555
    environment:
      - DISABLE_ANIMATION=false
      - DISABLE_HIDDEN_POLICY=true
      - SKIP_AUTH=false
      - MEMORY=16384
      - CORES=16
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./android_avd:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      - /dev/kvm:/dev/kvm

  android-emulator-cuda:
    build:
      context: .
      dockerfile: ./Dockerfile.gpu
      args:
        - API_LEVEL=34
        - CMD_LINE_VERSION=11076708_latest
        - IMG_TYPE=google_apis
    ports:
      - 5554:5554
      - 127.0.0.1:5555:5555
    environment:
      - DISABLE_ANIMATION=false
      - DISABLE_HIDDEN_POLICY=true
      - SKIP_AUTH=false
      - MEMORY=16384
      - CORES=16
    privileged: true
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
